### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by yochannah** [intermine/im-docs#27]
I was going to suggest to someone that they could base their contributing guidelines on [ours](http://intermine.readthedocs.io/en/latest/about/get-involved/), but I've noticed there is no licence in this repo. Would it be ok to add one? 

Ideally a flexible non-viral licence like [MIT](https://tldrlegal.com/license/mit-license).

**Comment by justincc** [comment]
Wouldn't a documentation license like CC0 be most suitable rather than a
code one?

+1 on the non-virality.  Viral licenses are suitable in some situations,
but imo code funded by the taxpayer should be non-viral to allow widest
possible use by companies that have also paid for it through taxes.  My
preferred is Apache 2.0 in those situations.

**Comment by julie-sullivan** [comment]
adding MIT
